## ANALISIS DE DATOS DE COMIDA (FOOD)

El presente es para analizar los datos de las comidas, el cual es un registro manual por cada usuario

In [17]:
# Importando Pandas y otras librerias
import pandas as pd
import numpy as np

In [18]:
# Parametros para calcular los valores
INTERVALO_2H = '2h'
INTERVALO_8H = '8h'
INTERVALO_24H = '24h'

In [19]:
PACIENTE = '003'
PATH_FOLDER = 'G:\\Dataset\\big-ideas-lab-glycemic-variability-and-wearable-device-data-1.1.2\\'+PACIENTE+'\\'

In [20]:
# Leyendo el CSV
food_values = pd.read_csv(PATH_FOLDER + 'Food_Log_'+PACIENTE+'.csv', engine='python', na_values="not available")

In [21]:
food_values.head(20)

,date,time,time_begin,time_end,logged_food,amount,unit,searched_food,calorie,total_carb,dietary_fiber,sugar,protein,total_fat
0,2020-02-22,10:30:00,2020-02-22 10:30:00,Chicken Nuggets,8.0,piece,Chicken Nuggets,393.0,19.0,0.1,20.0,NaN,NaN,NaN
1,2020-02-22,10:30:00,2020-02-22 10:30:00,Superfood Salad,4.0,fluid ounce,(Papa John's Salads & Produce) Superfood Salad,170.0,14.0,7.0,5.0,NaN,NaN,NaN
2,2020-02-22,14:30:00,2020-02-22 14:30:00,Dots Gumdrops,11.0,piece,Dots Gumdrop,130.0,33.0,21.0,0.0,NaN,NaN,NaN
3,2020-02-22,18:55:00,2020-02-22 18:55:00,Power Smoothie,9.0,fluid ounce,(Smoothie King) Power Punch Plus Smoothie,202.5,43.7,38.7,5.0,NaN,NaN,NaN
4,2020-02-22,20:20:00,2020-02-22 20:20:00,Salad,9.0,ounce,Salad,60.0,13.0,3.5,3.7,NaN,NaN,NaN
5,2020-02-22,20:20:00,2020-02-22 20:20:00,French Dressing,1.0,fluid ounce,Ranch Dressing,129.0,1.8,1.4,0.4,NaN,NaN,NaN
6,2020-02-22,20:20:00,2020-02-22 20:20:00,Spaghetti,20.0,ounce,Spaghetti,852.0,171.0,6.1,30.0,NaN,NaN,NaN
7,2020-02-23,05:30:00,2020-02-23 05:30:00,Milk,4.0,ounce,(Natrel) Lactose Free 2% Partly Skimmed Milk,60.0,4.5,4.0,6.0,NaN,NaN,NaN
8,2020-02-23,05:30:00,2020-02-23 05:30:00,Cornflakes,1.5,cup,(Kellogg's) Frosted Flakes,220.0,52.0,20.0,2.0,NaN,NaN,NaN
9,2020-02-23,12:00:00,2020-02-23 12:00:00,Spaghetti,12.0,ounce,Spaghetti,511.2,102.6,3.7,18.0,NaN,NaN,NaN
10,2020-02-23,16:03:00,2020-02-23 16:03:00,Tortilla Chips,2.0,ounce,Tortilla Chips,268.0,38.0,0.4,4.0,NaN,NaN,NaN
11,2020-02-23,16:03:00,2020-02-23 16:03:00,Salsa,2.0,ounce,Salsa,8.2,1.9,1.1,0.4,NaN,NaN,NaN
12,2020-02-23,18:09:00,2020-02-23 18:09:00,Crab Cakes,8.0,ounce,Crab Cakes,391.0,16.0,3.2,25.0,NaN,NaN,NaN
13,2020-02-23,18:09:00,2020-02-23 18:09:00,Brussel Sprouts,12.0,ounce,Brussel Sprouts,122.0,24.0,5.9,8.7,NaN,NaN,NaN
14,2020-02-23,21:00:00,2020-02-23 21:00:00,Tortilla Chips,2.0,ounce,Tortilla Chips,268.0,38.0,0.4,4.0,NaN,NaN,NaN
15,2020-02-24,10:00:00,2020-02-24 10:00:00,Greek Yogurt Power Smoothie,9.0,ounce,"(Powerful Smoothie) Greek Yogurt Smoothie, Str...",180.0,16.0,12.0,20.0,NaN,NaN,NaN
16,2020-02-24,13:00:00,2020-02-24 13:00:00,Shrimp,8.0,ounce,Shrimp,270.0,3.4,0.0,52.0,NaN,NaN,NaN
17,2020-02-24,13:00:00,2020-02-24 13:00:00,Clam Chowder,8.0,ounce,Clam Chowder,201.0,21.0,0.6,6.6,NaN,NaN,NaN
18,2020-02-24,20:00:00,2020-02-24 20:00:00,Carne Asada Steak,8.0,ounce,Carne Asada,498.0,0.5,0.1,59.0,NaN,NaN,NaN
19,2020-02-24,20:00:00,2020-02-24 20:00:00,Beans,2.0,ounce,Beans,53.0,12.0,4.5,2.7,NaN,NaN,NaN

In [22]:
food_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           58 non-null     object
 1   time           58 non-null     object
 2   time_begin     58 non-null     object
 3   time_end       58 non-null     object
 4   logged_food    57 non-null     float64
 5   amount         57 non-null     object
 6   unit           57 non-null     object
 7   searched_food  58 non-null     float64
 8   calorie        58 non-null     float64
 9   total_carb     58 non-null     float64
 10  dietary_fiber  58 non-null     float64
 11  sugar          0 non-null      float64
 12  protein        0 non-null      float64
 13  total_fat      0 non-null      float64
dtypes: float64(8), object(6)
memory usage: 6.5+ KB

In [23]:
food_values.count()

date             58
time             58
time_begin       58
time_end         58
logged_food      57
amount           57
unit             57
searched_food    58
calorie          58
total_carb       58
dietary_fiber    58
sugar             0
protein           0
total_fat         0
dtype: int64

### Trabajando con Datetime
Lo primero sera convertir los datetime a el formato correcto, ya que lo esta detectando como object, lo siguiente sera colocar como index las fechas y al final agrupar por cada 2, 8 y 24 horas los datos para obtener la sumatoria y media

In [24]:
# Convertimos en fechas los datimetimes
food_values['time_begin'] = pd.to_datetime(food_values['time_begin'])

In [25]:
food_values.head()

,date,time,time_begin,time_end,logged_food,amount,unit,searched_food,calorie,total_carb,dietary_fiber,sugar,protein,total_fat
0,2020-02-22,10:30:00,2020-02-22 10:30:00,Chicken Nuggets,8.0,piece,Chicken Nuggets,393.0,19.0,0.1,20.0,NaN,NaN,NaN
1,2020-02-22,10:30:00,2020-02-22 10:30:00,Superfood Salad,4.0,fluid ounce,(Papa John's Salads & Produce) Superfood Salad,170.0,14.0,7.0,5.0,NaN,NaN,NaN
2,2020-02-22,14:30:00,2020-02-22 14:30:00,Dots Gumdrops,11.0,piece,Dots Gumdrop,130.0,33.0,21.0,0.0,NaN,NaN,NaN
3,2020-02-22,18:55:00,2020-02-22 18:55:00,Power Smoothie,9.0,fluid ounce,(Smoothie King) Power Punch Plus Smoothie,202.5,43.7,38.7,5.0,NaN,NaN,NaN
4,2020-02-22,20:20:00,2020-02-22 20:20:00,Salad,9.0,ounce,Salad,60.0,13.0,3.5,3.7,NaN,NaN,NaN

In [26]:
food_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           58 non-null     object
 1   time           58 non-null     object
 2   time_begin     58 non-null     datetime64[ns]
 3   time_end       58 non-null     object
 4   logged_food    57 non-null     float64
 5   amount         57 non-null     object
 6   unit           57 non-null     object
 7   searched_food  58 non-null     float64
 8   calorie        58 non-null     float64
 9   total_carb     58 non-null     float64
 10  dietary_fiber  58 non-null     float64
 11  sugar          0 non-null      float64
 12  protein        0 non-null      float64
 13  total_fat      0 non-null      float64
dtypes: datetime64[ns](1), float64(8), object(5)
memory usage: 6.5+ KB

In [27]:
# Definir una función para calcular el promedio de registros
def calculate_average_count(df, freq):
    resampled = df.resample(freq, on='time_begin').size()
    return resampled.mean()

In [28]:
# Empezamos por agrupar los valores importantes
# 2 horas
df_procesado_2h = food_values.resample(INTERVALO_2H, on='time_begin').agg({
    'calorie': ['sum', 'mean'],
    'total_carb': ['sum', 'mean'],
    'sugar': ['sum', 'mean'],
    'protein': ['sum', 'mean'],
})
# # 8 horas 
df_procesado_8h = food_values.resample(INTERVALO_8H, on='time_begin').agg({
    'calorie': ['sum', 'mean'],
    'total_carb': ['sum', 'mean'],
    'sugar': ['sum', 'mean'],
    'protein': ['sum', 'mean'],
})
# # 24 horas 
df_procesado_24h = food_values.resample(INTERVALO_24H, on='time_begin').agg({
    'calorie': ['sum', 'mean'],
    'total_carb': ['sum', 'mean'],
    'sugar': ['sum', 'mean'],
    'protein': ['sum', 'mean'],
})

df_procesado_24h

           calorie            total_carb            sugar      protein
               sum       mean        sum       mean   sum mean     sum mean
time_begin
2020-02-22   295.5  42.214286       77.8  11.114286   0.0  NaN     0.0  NaN
2020-02-23   277.0  34.625000       38.7   4.837500   0.0  NaN     0.0  NaN
2020-02-24   146.3  18.287500       24.8   3.100000   0.0  NaN     0.0  NaN
2020-02-25   254.1  19.546154      141.9  10.915385   0.0  NaN     0.0  NaN
2020-02-26   192.9  38.580000       87.8  17.560000   0.0  NaN     0.0  NaN
2020-02-27    99.5  14.214286       47.6   6.800000   0.0  NaN     0.0  NaN
2020-02-28    46.4  11.600000       23.9   5.975000   0.0  NaN     0.0  NaN
2020-02-29    90.8  18.160000       42.3   8.460000   0.0  NaN     0.0  NaN
2020-03-01    82.0  82.000000       40.0  40.000000   0.0  NaN     0.0  NaN

In [29]:


# Agregar columnas para contar la cantidad de registros en cada intervalo de 2 horas
df_procesado_2h['cantidad_comidas'] = food_values.resample(INTERVALO_2H, on='time_begin').size()
df_procesado_8h['cantidad_comidas'] = food_values.resample(INTERVALO_8H, on='time_begin').size()
df_procesado_24h['cantidad_comidas'] = food_values.resample(INTERVALO_24H, on='time_begin').size()
df_procesado_2h

                    calorie       total_carb        sugar      protein       \
                        sum  mean        sum   mean   sum mean     sum mean
time_begin
2020-02-22 10:00:00    33.0  16.5        7.1   3.55   0.0  NaN     0.0  NaN
2020-02-22 12:00:00     0.0   NaN        0.0    NaN   0.0  NaN     0.0  NaN
2020-02-22 14:00:00    33.0  33.0       21.0  21.00   0.0  NaN     0.0  NaN
2020-02-22 16:00:00     0.0   NaN        0.0    NaN   0.0  NaN     0.0  NaN
2020-02-22 18:00:00    43.7  43.7       38.7  38.70   0.0  NaN     0.0  NaN
...                     ...   ...        ...    ...   ...  ...     ...  ...
2020-03-01 00:00:00     0.0   NaN        0.0    NaN   0.0  NaN     0.0  NaN
2020-03-01 02:00:00     0.0   NaN        0.0    NaN   0.0  NaN     0.0  NaN
2020-03-01 04:00:00     0.0   NaN        0.0    NaN   0.0  NaN     0.0  NaN
2020-03-01 06:00:00     0.0   NaN        0.0    NaN   0.0  NaN     0.0  NaN
2020-03-01 08:00:00    82.0  82.0       40.0  40.00   0.0  NaN     0.0  NaN

                    cantidad_comidas

time_begin
2020-02-22 10:00:00                2
2020-02-22 12:00:00                0
2020-02-22 14:00:00                1
2020-02-22 16:00:00                0
2020-02-22 18:00:00                1
...                              ...
2020-03-01 00:00:00                0
2020-03-01 02:00:00                0
2020-03-01 04:00:00                0
2020-03-01 06:00:00                0
2020-03-01 08:00:00                1

[96 rows x 9 columns]

In [30]:
# Ahora agregamos la media
average_count_2h = calculate_average_count(food_values, INTERVALO_2H)
df_procesado_2h['media_comidas'] = average_count_2h

average_count_8h = calculate_average_count(food_values, INTERVALO_8H)
df_procesado_8h['media_comidas'] = average_count_8h

average_count_24h = calculate_average_count(food_values, INTERVALO_24H)
df_procesado_24h['media_comidas'] = average_count_24h

df_procesado_24h

           calorie            total_carb            sugar      protein       \
               sum       mean        sum       mean   sum mean     sum mean
time_begin
2020-02-22   295.5  42.214286       77.8  11.114286   0.0  NaN     0.0  NaN
2020-02-23   277.0  34.625000       38.7   4.837500   0.0  NaN     0.0  NaN
2020-02-24   146.3  18.287500       24.8   3.100000   0.0  NaN     0.0  NaN
2020-02-25   254.1  19.546154      141.9  10.915385   0.0  NaN     0.0  NaN
2020-02-26   192.9  38.580000       87.8  17.560000   0.0  NaN     0.0  NaN
2020-02-27    99.5  14.214286       47.6   6.800000   0.0  NaN     0.0  NaN
2020-02-28    46.4  11.600000       23.9   5.975000   0.0  NaN     0.0  NaN
2020-02-29    90.8  18.160000       42.3   8.460000   0.0  NaN     0.0  NaN
2020-03-01    82.0  82.000000       40.0  40.000000   0.0  NaN     0.0  NaN

           cantidad_comidas media_comidas

time_begin
2020-02-22                7      6.444444
2020-02-23                8      6.444444
2020-02-24                8      6.444444
2020-02-25               13      6.444444
2020-02-26                5      6.444444
2020-02-27                7      6.444444
2020-02-28                4      6.444444
2020-02-29                5      6.444444
2020-03-01                1      6.444444

In [31]:
# Renombrar las columnas para mayor claridad
df_procesado_2h.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_procesado_2h.columns.values]
df_procesado_8h.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_procesado_8h.columns.values]
df_procesado_24h.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_procesado_24h.columns.values]

print(df_procesado_8h)

                     calorie_sum  calorie_mean  total_carb_sum  \
time_begin
2020-02-22 08:00:00         66.0     22.000000            28.1
2020-02-22 16:00:00        229.5     57.375000            49.7
2020-02-23 00:00:00         56.5     28.250000            24.0
2020-02-23 08:00:00        102.6    102.600000             3.7
2020-02-23 16:00:00        117.9     23.580000            11.0
2020-02-24 00:00:00          0.0           NaN             0.0
2020-02-24 08:00:00         40.4     13.466667            12.6
2020-02-24 16:00:00        105.9     21.180000            12.2
2020-02-25 00:00:00         56.5     28.250000            24.0
2020-02-25 08:00:00         27.1      5.420000            21.2
2020-02-25 16:00:00        170.5     28.416667            96.7
2020-02-26 00:00:00          0.0           NaN             0.0
2020-02-26 08:00:00        124.0    124.000000            84.0
2020-02-26 16:00:00         68.9     17.225000             3.8
2020-02-27 00:00:00         56.5     28.250000            24.0
2020-02-27 08:00:00         16.0      4.000000             1.6
2020-02-27 16:00:00         27.0     27.000000            22.0
2020-02-28 00:00:00          0.0           NaN             0.0
2020-02-28 08:00:00         13.0     13.000000            11.0
2020-02-28 16:00:00         33.4     11.133333            12.9
2020-02-29 00:00:00          0.0           NaN             0.0
2020-02-29 08:00:00         74.5     24.833333            28.2
2020-02-29 16:00:00         16.3      8.150000            14.1
2020-03-01 00:00:00          0.0           NaN             0.0
2020-03-01 08:00:00         82.0     82.000000            40.0

                     total_carb_mean  sugar_sum  sugar_mean  protein_sum  \
time_begin
2020-02-22 08:00:00         9.366667        0.0         NaN          0.0
2020-02-22 16:00:00        12.425000        0.0         NaN          0.0
2020-02-23 00:00:00        12.000000        0.0         NaN          0.0
2020-02-23 08:00:00         3.700000        0.0         NaN          0.0
2020-02-23 16:00:00         2.200000        0.0         NaN          0.0
2020-02-24 00:00:00              NaN        0.0         NaN          0.0
2020-02-24 08:00:00         4.200000        0.0         NaN          0.0
2020-02-24 16:00:00         2.440000        0.0         NaN          0.0
2020-02-25 00:00:00        12.000000        0.0         NaN          0.0
2020-02-25 08:00:00         4.240000        0.0         NaN          0.0
2020-02-25 16:00:00        16.116667        0.0         NaN          0.0
2020-02-26 00:00:00              NaN        0.0         NaN          0.0
2020-02-26 08:00:00        84.000000        0.0         NaN          0.0
2020-02-26 16:00:00         0.950000        0.0         NaN          0.0
2020-02-27 00:00:00        12.000000        0.0         NaN          0.0
2020-02-27 08:00:00         0.400000        0.0         NaN          0.0
2020-02-27 16:00:00        22.000000        0.0         NaN          0.0
2020-02-28 00:00:00              NaN        0.0         NaN          0.0
2020-02-28 08:00:00        11.000000        0.0         NaN          0.0
2020-02-28 16:00:00         4.300000        0.0         NaN          0.0
2020-02-29 00:00:00              NaN        0.0         NaN          0.0
2020-02-29 08:00:00         9.400000        0.0         NaN          0.0
2020-02-29 16:00:00         7.050000        0.0         NaN          0.0
2020-03-01 00:00:00              NaN        0.0         NaN          0.0
2020-03-01 08:00:00        40.000000        0.0         NaN          0.0

                     protein_mean  cantidad_comidas_  media_comidas_
time_begin
2020-02-22 08:00:00           NaN                  3            2.32
2020-02-22 16:00:00           NaN                  4            2.32
2020-02-23 00:00:00           NaN                  2            2.32
2020-02-23 08:00:00           NaN                  1            2.32
2020-02-23 16:00:00           NaN                  5            2.32
2020-02-24 00:00:00           NaN                  0            2.32
2020-02-24 08:00:00           NaN                  3            2.32
2020-02-24 16:00:00           NaN                  5            2.32
2020-02-25 00:00:00           NaN                  2            2.32
2020-02-25 08:00:00           NaN                  5            2.32
2020-02-25 16:00:00           NaN                  6            2.32
2020-02-26 00:00:00           NaN                  0            2.32
2020-02-26 08:00:00           NaN                  1            2.32
2020-02-26 16:00:00           NaN                  4            2.32
2020-02-27 00:00:00           NaN                  2            2.32
2020-02-27 08:00:00           NaN                  4            2.32
2020-02-27 16:00:00           NaN                  1            2.32
2020-02-28 00:00:00           NaN                  0            2.32
2020-02-28 08:00:00           NaN                  1            2.32
2020-02-28 16:00:00           NaN                  3            2.32
2020-02-29 00:00:00           NaN                  0            2.32
2020-02-29 08:00:00           NaN                  3            2.32
2020-02-29 16:00:00           NaN                  2            2.32
2020-03-01 00:00:00           NaN                  0            2.32
2020-03-01 08:00:00           NaN                  1            2.32

In [32]:
df_procesado_8h.head()

,calorie_sum,calorie_mean,total_carb_sum,total_carb_mean,sugar_sum,sugar_mean,protein_sum,protein_mean,cantidad_comidas_,media_comidas_
time_begin,,,,,,,,,,
2020-02-22 08:00:00,66.0,22.000,28.1,9.366667,0.0,NaN,0.0,NaN,3,2.32
2020-02-22 16:00:00,229.5,57.375,49.7,12.425000,0.0,NaN,0.0,NaN,4,2.32
2020-02-23 00:00:00,56.5,28.250,24.0,12.000000,0.0,NaN,0.0,NaN,2,2.32
2020-02-23 08:00:00,102.6,102.600,3.7,3.700000,0.0,NaN,0.0,NaN,1,2.32
2020-02-23 16:00:00,117.9,23.580,11.0,2.200000,0.0,NaN,0.0,NaN,5,2.32

In [33]:
# Exportamos los resultados en un csv
df_procesado_2h.to_csv("Food_2h_"+PACIENTE+".csv")
df_procesado_8h.to_csv("Food_8h_"+PACIENTE+".csv")
df_procesado_24h.to_csv("Food_24h_"+PACIENTE+".csv")

### ARCHIVOS CSV GENERADOS CON EXITO PARA 2 HORAS, 8 HORAS Y 24 HORAS