## ANALISIS DE DATOS DE COMIDA (FOOD)

El presente es para analizar los datos de las comidas, el cual es un registro manual por cada usuario

In [243]:
# Importando Pandas y otras librerias
import pandas as pd
import numpy as np

In [244]:
# Parametros para calcular los valores
INTERVALO_2H = '2h'
INTERVALO_8H = '8h'
INTERVALO_24H = '24h'

In [245]:
PACIENTE = '015'
PATH_FOLDER = 'G:\\Dataset\\big-ideas-lab-glycemic-variability-and-wearable-device-data-1.1.2\\'+PACIENTE+'\\'

In [246]:
# Leyendo el CSV
food_values = pd.read_csv(PATH_FOLDER + 'Food_Log_'+PACIENTE+'.csv', engine='python', na_values="not available")

In [247]:
food_values.head(20)

,date,time_of_day,time_begin,time_end,logged_food,amount,unit,searched_food,calorie,total_carb,dietary_fiber,sugar,protein,total_fat
0,2/17/2020,10:00,2020-02-17 10:00:00,NaN,Coffee + skim milk,10,fluid ounce,NaN,35.0,4.5,0.0,4.7,3.4,0.1
1,2/17/2020,10:09,2020-02-17 10:09:00,10:13,Glucerna snack bar,40,grams,NaN,160.0,20.0,3.0,4.0,10.0,5.0
2,2/17/2020,15:50,2020-02-17 15:50:00,15:53,Small pc red velvet cake,NaN,NaN,NaN,368.0,36.0,0.3,25.0,4.2,23.0
3,2/17/2020,17:50,2020-02-17 17:50:00,18:10,Ruffles chips,3,oz,NaN,447.0,45.0,2.6,0.3,5.4,28.5
4,2/17/2020,20:30,2020-02-17 20:30:00,21:20,Panko breaded baked fish,8,oz,NaN,398.0,14.0,1.2,0.0,32.0,24.0
5,2/17/2020,20:30,2020-02-17 20:30:00,21:20,Celery,2,stalks,NaN,13.0,2.4,1.3,1.1,0.6,0.1
6,2/17/2020,20:30,2020-02-17 20:30:00,21:20,Onion,1,NaN,NaN,41.5,9.5,1.3,4.5,1.3,0.2
7,2/18/2020,5:45,2020-02-18 05:45:00,6:20,Coffee + skim milk,10,fluid ounce,NaN,35.0,4.5,0.0,4.7,3.4,0.1
8,2/18/2020,7:40,2020-02-18 07:40:00,NaN,Coffee,10,fluid ounce,NaN,35.0,4.5,0.0,4.7,3.4,0.1
9,2/18/2020,7:59,2020-02-18 07:59:00,8:05,Standard breakfast,NaN,NaN,NaN,280.0,56.5,1.0,24.0,8.0,2.5
10,2/18/2020,10:40,2020-02-18 10:40:00,NaN,Muffin,NaN,NaN,NaN,424.0,60.0,1.3,35.5,5.0,18.0
11,2/18/2020,13:10,2020-02-18 13:10:00,13:12,Northern Harvest Sweet + Spicy Chunk light Tuna,2.5 oz,NaN,NaN,80.0,4.0,0.0,3.5,16.0,0.5
12,2/18/2020,13:50,2020-02-18 13:50:00,13:55,multigrain cakes,5,crackers,NaN,200.0,28.0,1.5,5.0,3.0,8.4
13,2/18/2020,18:10,2020-02-18 18:10:00,19:13,BLT salad,NaN,NaN,NaN,409.0,16.5,3.8,3.8,12.5,33.0
14,2/18/2020,18:10,2020-02-18 18:10:00,NaN,Whole grapefruit,1,NaN,NaN,104.0,26.0,4.0,17.0,1.9,0.3
15,2/19/2020,1:10,2020-02-19 01:10:00,NaN,Slim Fast,NaN,NaN,NaN,171.0,2.5,1.2,1.8,19.5,8.5
16,2/19/2020,3:30,2020-02-19 03:30:00,3:45,Coffee + skim milk,10,fluid ounce,NaN,35.0,4.5,0.0,4.7,3.4,0.1
17,2/19/2020,4:45,2020-02-19 04:45:00,4:50,Friendly Farm Cottage Cheese 1% milkfat,1/3 cup,NaN,NaN,70.0,2.4,0.0,1.9,7.9,3.1
18,2/19/2020,4:45,2020-02-19 04:45:00,NaN,Harris Teeter canned sliced peaches,3,slices,NaN,55.0,14.5,1.6,13.0,0.8,0.0
19,2/19/2020,4:45,2020-02-19 04:45:00,NaN,Peach juice,3,Tbsp,NaN,25.0,6.6,0.3,5.7,0.1,0.0

In [248]:
food_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           77 non-null     object
 1   time_of_day    77 non-null     object
 2   time_begin     77 non-null     object
 3   time_end       47 non-null     object
 4   logged_food    77 non-null     object
 5   amount         45 non-null     object
 6   unit           36 non-null     object
 7   searched_food  0 non-null      float64
 8   calorie        77 non-null     float64
 9   total_carb     77 non-null     float64
 10  dietary_fiber  77 non-null     float64
 11  sugar          77 non-null     float64
 12  protein        77 non-null     float64
 13  total_fat      77 non-null     float64
dtypes: float64(7), object(7)
memory usage: 8.6+ KB

In [249]:
food_values.count()

date             77
time_of_day      77
time_begin       77
time_end         47
logged_food      77
amount           45
unit             36
searched_food     0
calorie          77
total_carb       77
dietary_fiber    77
sugar            77
protein          77
total_fat        77
dtype: int64

In [250]:
food_values["date"].head(20)

0     2/17/2020
1     2/17/2020
2     2/17/2020
3     2/17/2020
4     2/17/2020
5     2/17/2020
6     2/17/2020
7     2/18/2020
8     2/18/2020
9     2/18/2020
10    2/18/2020
11    2/18/2020
12    2/18/2020
13    2/18/2020
14    2/18/2020
15    2/19/2020
16    2/19/2020
17    2/19/2020
18    2/19/2020
19    2/19/2020
Name: date, dtype: object

### Trabajando con Datetime
Lo primero sera convertir los datetime a el formato correcto, ya que lo esta detectando como object, lo siguiente sera colocar como index las fechas y al final agrupar por cada 2, 8 y 24 horas los datos para obtener la sumatoria y media

In [251]:
# Convertimos en fechas los datimetimes
food_values['time_begin'] = pd.to_datetime(food_values['time_begin'])

In [252]:
food_values.head()

,date,time_of_day,time_begin,time_end,logged_food,amount,unit,searched_food,calorie,total_carb,dietary_fiber,sugar,protein,total_fat
0,2/17/2020,10:00,2020-02-17 10:00:00,NaN,Coffee + skim milk,10,fluid ounce,NaN,35.0,4.5,0.0,4.7,3.4,0.1
1,2/17/2020,10:09,2020-02-17 10:09:00,10:13,Glucerna snack bar,40,grams,NaN,160.0,20.0,3.0,4.0,10.0,5.0
2,2/17/2020,15:50,2020-02-17 15:50:00,15:53,Small pc red velvet cake,NaN,NaN,NaN,368.0,36.0,0.3,25.0,4.2,23.0
3,2/17/2020,17:50,2020-02-17 17:50:00,18:10,Ruffles chips,3,oz,NaN,447.0,45.0,2.6,0.3,5.4,28.5
4,2/17/2020,20:30,2020-02-17 20:30:00,21:20,Panko breaded baked fish,8,oz,NaN,398.0,14.0,1.2,0.0,32.0,24.0

In [253]:
food_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           77 non-null     object
 1   time_of_day    77 non-null     object
 2   time_begin     77 non-null     datetime64[ns]
 3   time_end       47 non-null     object
 4   logged_food    77 non-null     object
 5   amount         45 non-null     object
 6   unit           36 non-null     object
 7   searched_food  0 non-null      float64
 8   calorie        77 non-null     float64
 9   total_carb     77 non-null     float64
 10  dietary_fiber  77 non-null     float64
 11  sugar          77 non-null     float64
 12  protein        77 non-null     float64
 13  total_fat      77 non-null     float64
dtypes: datetime64[ns](1), float64(7), object(6)
memory usage: 8.6+ KB

In [254]:
# Definir una función para calcular el promedio de registros
def calculate_average_count(df, freq):
    resampled = df.resample(freq, on='time_begin').size()
    return resampled.mean()

In [255]:
# Empezamos por agrupar los valores importantes
# 2 horas
df_procesado_2h = food_values.resample(INTERVALO_2H, on='time_begin').agg({
    'calorie': ['sum', 'mean'],
    'total_carb': ['sum', 'mean'],
    'sugar': ['sum', 'mean'],
    'protein': ['sum', 'mean'],
})
# # 8 horas 
df_procesado_8h = food_values.resample(INTERVALO_8H, on='time_begin').agg({
    'calorie': ['sum', 'mean'],
    'total_carb': ['sum', 'mean'],
    'sugar': ['sum', 'mean'],
    'protein': ['sum', 'mean'],
})
# # 24 horas 
df_procesado_24h = food_values.resample(INTERVALO_24H, on='time_begin').agg({
    'calorie': ['sum', 'mean'],
    'total_carb': ['sum', 'mean'],
    'sugar': ['sum', 'mean'],
    'protein': ['sum', 'mean'],
})

df_procesado_24h

           calorie             total_carb             sugar             \
               sum        mean        sum       mean    sum       mean
time_begin
2020-02-17  1462.5  208.928571      131.4  18.771429   39.6   5.657143
2020-02-18  1567.0  195.875000      200.0  25.000000   98.2  12.275000
2020-02-19  3661.0  215.352941      395.1  23.241176  156.5   9.205882
2020-02-20  1621.0  180.111111      159.0  17.666667   69.9   7.766667
2020-02-21  2920.0  243.333333      344.9  28.741667  204.4  17.033333
2020-02-22  2285.0  163.214286      172.3  12.307143   92.8   6.628571
2020-02-23  1736.0  192.888889      263.6  29.288889   89.1   9.900000
2020-02-24     0.0         NaN        0.0        NaN    0.0        NaN
2020-02-25   654.0  654.000000       82.0  82.000000   40.0  40.000000

           protein
               sum       mean
time_begin
2020-02-17    56.9   8.128571
2020-02-18    53.2   6.650000
2020-02-19   117.9   6.935294
2020-02-20    72.0   8.000000
2020-02-21   121.6  10.133333
2020-02-22   114.9   8.207143
2020-02-23    54.0   6.000000
2020-02-24     0.0        NaN
2020-02-25    26.0  26.000000

In [256]:


# Agregar columnas para contar la cantidad de registros en cada intervalo de 2 horas
df_procesado_2h['cantidad_comidas'] = food_values.resample(INTERVALO_2H, on='time_begin').size()
df_procesado_8h['cantidad_comidas'] = food_values.resample(INTERVALO_8H, on='time_begin').size()
df_procesado_24h['cantidad_comidas'] = food_values.resample(INTERVALO_24H, on='time_begin').size()
df_procesado_2h

                    calorie        total_carb        sugar        protein  \
                        sum   mean        sum   mean   sum   mean     sum
time_begin
2020-02-17 10:00:00   195.0   97.5       24.5  12.25   8.7   4.35    13.4
2020-02-17 12:00:00     0.0    NaN        0.0    NaN   0.0    NaN     0.0
2020-02-17 14:00:00   368.0  368.0       36.0  36.00  25.0  25.00     4.2
2020-02-17 16:00:00   447.0  447.0       45.0  45.00   0.3   0.30     5.4
2020-02-17 18:00:00     0.0    NaN        0.0    NaN   0.0    NaN     0.0
...                     ...    ...        ...    ...   ...    ...     ...
2020-02-24 22:00:00     0.0    NaN        0.0    NaN   0.0    NaN     0.0
2020-02-25 00:00:00     0.0    NaN        0.0    NaN   0.0    NaN     0.0
2020-02-25 02:00:00     0.0    NaN        0.0    NaN   0.0    NaN     0.0
2020-02-25 04:00:00     0.0    NaN        0.0    NaN   0.0    NaN     0.0
2020-02-25 06:00:00   654.0  654.0       82.0  82.00  40.0  40.00    26.0

                          cantidad_comidas
                     mean
time_begin
2020-02-17 10:00:00   6.7                2
2020-02-17 12:00:00   NaN                0
2020-02-17 14:00:00   4.2                1
2020-02-17 16:00:00   5.4                1
2020-02-17 18:00:00   NaN                0
...                   ...              ...
2020-02-24 22:00:00   NaN                0
2020-02-25 00:00:00   NaN                0
2020-02-25 02:00:00   NaN                0
2020-02-25 04:00:00   NaN                0
2020-02-25 06:00:00  26.0                1

[95 rows x 9 columns]

In [257]:
# Ahora agregamos la media
average_count_2h = calculate_average_count(food_values, INTERVALO_2H)
df_procesado_2h['media_comidas'] = average_count_2h

average_count_8h = calculate_average_count(food_values, INTERVALO_8H)
df_procesado_8h['media_comidas'] = average_count_8h

average_count_24h = calculate_average_count(food_values, INTERVALO_24H)
df_procesado_24h['media_comidas'] = average_count_24h

df_procesado_24h

           calorie             total_carb             sugar             \
               sum        mean        sum       mean    sum       mean
time_begin
2020-02-17  1462.5  208.928571      131.4  18.771429   39.6   5.657143
2020-02-18  1567.0  195.875000      200.0  25.000000   98.2  12.275000
2020-02-19  3661.0  215.352941      395.1  23.241176  156.5   9.205882
2020-02-20  1621.0  180.111111      159.0  17.666667   69.9   7.766667
2020-02-21  2920.0  243.333333      344.9  28.741667  204.4  17.033333
2020-02-22  2285.0  163.214286      172.3  12.307143   92.8   6.628571
2020-02-23  1736.0  192.888889      263.6  29.288889   89.1   9.900000
2020-02-24     0.0         NaN        0.0        NaN    0.0        NaN
2020-02-25   654.0  654.000000       82.0  82.000000   40.0  40.000000

           protein            cantidad_comidas media_comidas
               sum       mean
time_begin
2020-02-17    56.9   8.128571                7      8.555556
2020-02-18    53.2   6.650000                8      8.555556
2020-02-19   117.9   6.935294               17      8.555556
2020-02-20    72.0   8.000000                9      8.555556
2020-02-21   121.6  10.133333               12      8.555556
2020-02-22   114.9   8.207143               14      8.555556
2020-02-23    54.0   6.000000                9      8.555556
2020-02-24     0.0        NaN                0      8.555556
2020-02-25    26.0  26.000000                1      8.555556

In [258]:
# Renombrar las columnas para mayor claridad
df_procesado_2h.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_procesado_2h.columns.values]
df_procesado_8h.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_procesado_8h.columns.values]
df_procesado_24h.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_procesado_24h.columns.values]

print(df_procesado_8h)

                     calorie_sum  calorie_mean  total_carb_sum  \
time_begin
2020-02-17 08:00:00        563.0    187.666667            60.5
2020-02-17 16:00:00        899.5    224.875000            70.9
2020-02-18 00:00:00        350.0    116.666667            65.5
2020-02-18 08:00:00        704.0    234.666667            92.0
2020-02-18 16:00:00        513.0    256.500000            42.5
2020-02-19 00:00:00        461.0     65.857143            48.0
2020-02-19 08:00:00       2092.0    298.857143           187.1
2020-02-19 16:00:00       1108.0    369.333333           160.0
2020-02-20 00:00:00        350.0    116.666667            65.5
2020-02-20 08:00:00        171.0    171.000000             2.5
2020-02-20 16:00:00       1100.0    220.000000            91.0
2020-02-21 00:00:00        938.0    312.666667           125.4
2020-02-21 08:00:00       1125.0    225.000000           134.0
2020-02-21 16:00:00        857.0    214.250000            85.5
2020-02-22 00:00:00         35.0     35.000000             4.5
2020-02-22 08:00:00       1047.0    104.700000           106.4
2020-02-22 16:00:00       1203.0    401.000000            61.4
2020-02-23 00:00:00         35.0     35.000000             4.5
2020-02-23 08:00:00       1176.0    235.200000           170.0
2020-02-23 16:00:00        525.0    175.000000            89.1
2020-02-24 00:00:00          0.0           NaN             0.0
2020-02-24 08:00:00          0.0           NaN             0.0
2020-02-24 16:00:00          0.0           NaN             0.0
2020-02-25 00:00:00        654.0    654.000000            82.0

                     total_carb_mean  sugar_sum  sugar_mean  protein_sum  \
time_begin
2020-02-17 08:00:00        20.166667       33.7   11.233333         17.6
2020-02-17 16:00:00        17.725000        5.9    1.475000         39.3
2020-02-18 00:00:00        21.833333       33.4   11.133333         14.8
2020-02-18 08:00:00        30.666667       44.0   14.666667         24.0
2020-02-18 16:00:00        21.250000       20.8   10.400000         14.4
2020-02-19 00:00:00         6.857143       32.8    4.685714         37.1
2020-02-19 08:00:00        26.728571       56.7    8.100000         63.5
2020-02-19 16:00:00        53.333333       67.0   22.333333         17.3
2020-02-20 00:00:00        21.833333       33.4   11.133333         14.8
2020-02-20 08:00:00         2.500000        1.8    1.800000         19.5
2020-02-20 16:00:00        18.200000       34.7    6.940000         37.7
2020-02-21 00:00:00        41.800000       75.1   25.033333         21.4
2020-02-21 08:00:00        26.800000       69.0   13.800000         58.4
2020-02-21 16:00:00        21.375000       60.3   15.075000         41.8
2020-02-22 00:00:00         4.500000        4.7    4.700000          3.4
2020-02-22 08:00:00        10.640000       44.4    4.440000         61.0
2020-02-22 16:00:00        20.466667       43.7   14.566667         50.5
2020-02-23 00:00:00         4.500000        4.7    4.700000          3.4
2020-02-23 08:00:00        34.000000       68.6   13.720000         36.7
2020-02-23 16:00:00        29.700000       15.8    5.266667         13.9
2020-02-24 00:00:00              NaN        0.0         NaN          0.0
2020-02-24 08:00:00              NaN        0.0         NaN          0.0
2020-02-24 16:00:00              NaN        0.0         NaN          0.0
2020-02-25 00:00:00        82.000000       40.0   40.000000         26.0

                     protein_mean  cantidad_comidas_  media_comidas_
time_begin
2020-02-17 08:00:00      5.866667                  3        3.208333
2020-02-17 16:00:00      9.825000                  4        3.208333
2020-02-18 00:00:00      4.933333                  3        3.208333
2020-02-18 08:00:00      8.000000                  3        3.208333
2020-02-18 16:00:00      7.200000                  2        3.208333
2020-02-19 00:00:00      5.300000                  7        3.208333
2020-02-19 08:00:00      9.071429                  7        3.208333
2020-02-19 16:00:00      5.766667                  3        3.208333
2020-02-20 00:00:00      4.933333                  3        3.208333
2020-02-20 08:00:00     19.500000                  1        3.208333
2020-02-20 16:00:00      7.540000                  5        3.208333
2020-02-21 00:00:00      7.133333                  3        3.208333
2020-02-21 08:00:00     11.680000                  5        3.208333
2020-02-21 16:00:00     10.450000                  4        3.208333
2020-02-22 00:00:00      3.400000                  1        3.208333
2020-02-22 08:00:00      6.100000                 10        3.208333
2020-02-22 16:00:00     16.833333                  3        3.208333
2020-02-23 00:00:00      3.400000                  1        3.208333
2020-02-23 08:00:00      7.340000                  5        3.208333
2020-02-23 16:00:00      4.633333                  3        3.208333
2020-02-24 00:00:00           NaN                  0        3.208333
2020-02-24 08:00:00           NaN                  0        3.208333
2020-02-24 16:00:00           NaN                  0        3.208333
2020-02-25 00:00:00     26.000000                  1        3.208333

In [259]:
df_procesado_8h.head()

,calorie_sum,calorie_mean,total_carb_sum,total_carb_mean,sugar_sum,sugar_mean,protein_sum,protein_mean,cantidad_comidas_,media_comidas_
time_begin,,,,,,,,,,
2020-02-17 08:00:00,563.0,187.666667,60.5,20.166667,33.7,11.233333,17.6,5.866667,3,3.208333
2020-02-17 16:00:00,899.5,224.875000,70.9,17.725000,5.9,1.475000,39.3,9.825000,4,3.208333
2020-02-18 00:00:00,350.0,116.666667,65.5,21.833333,33.4,11.133333,14.8,4.933333,3,3.208333
2020-02-18 08:00:00,704.0,234.666667,92.0,30.666667,44.0,14.666667,24.0,8.000000,3,3.208333
2020-02-18 16:00:00,513.0,256.500000,42.5,21.250000,20.8,10.400000,14.4,7.200000,2,3.208333

In [260]:
# Exportamos los resultados en un csv
df_procesado_2h.to_csv("Food_2h_"+PACIENTE+".csv")
df_procesado_8h.to_csv("Food_8h_"+PACIENTE+".csv")
df_procesado_24h.to_csv("Food_24h_"+PACIENTE+".csv")

### ARCHIVOS CSV GENERADOS CON EXITO PARA 2 HORAS, 8 HORAS Y 24 HORAS