## ANALISIS DE DATOS DE COMIDA (FOOD)

El presente es para analizar los datos de las comidas, el cual es un registro manual por cada usuario

In [1]:
# Importando Pandas y otras librerias
import pandas as pd
import numpy as np

In [2]:
# Parametros para calcular los valores
INTERVALO_2H = '2h'
INTERVALO_8H = '8h'
INTERVALO_24H = '24h'

In [3]:
# Leyendo el CSV
food_values = pd.read_csv('Food_Log_016.csv', engine='python', na_values="not available")

In [4]:
food_values.head(20)

,date,time_of_day,time_begin,time_end,logged_food,amount,unit,searched_food,calorie,total_carb,dietary_fiber,sugar,protein,total_fat
0,2/21/2020,6:30,2020-02-21 06:30:00,NaN,Salmon cakes,2,NaN,NaN,736,58.0,4.6,3.8,32.0,42.0
1,2/21/2020,6:30,2020-02-21 06:30:00,NaN,Large coffee with heavy cream,NaN,NaN,NaN,84,2.6,0.0,2.6,2.4,7.0
2,2/21/2020,8:30,2020-02-21 08:30:00,NaN,Standard breakfast,NaN,NaN,NaN,280,56.5,1.0,24.0,8.0,2.5
3,2/21/2020,13:15,2020-02-21 13:15:00,NaN,Ham and cheese sandwhich,NaN,NaN,NaN,517,28.0,2.3,3.6,28.0,32.0
4,2/21/2020,13:15,2020-02-21 13:15:00,NaN,Brownies,2 small,NaN,NaN,466,50.0,NaN,28.0,6.2,30.0
5,2/21/2020,13:15,2020-02-21 13:15:00,NaN,Peanut Butter,1,Tbsp,NaN,94,3.9,0.9,1.1,3.5,8.0
6,2/21/2020,16:30,2020-02-21 16:30:00,NaN,Two slices of bread,2,slices,NaN,154,28.0,1.6,3.2,5.2,1.9
7,2/21/2020,16:30,2020-02-21 16:30:00,NaN,Butter,2,Tbsp,NaN,204,0.0,0.0,0.0,0.2,24.0
8,2/21/2020,19:30,2020-02-21 19:30:00,NaN,"Chipotle burrito bowl chicken and steak, black...",NaN,NaN,NaN,1008,117.0,14.0,5.6,49.0,38.0
9,2/21/2020,19:30,2020-02-21 19:30:00,NaN,2 Yuengling beers,2,12oz bears,NaN,312,26.4,0.0,0.0,3.4,0.0
10,2/22/2020,8:00,2020-02-22 08:00:00,NaN,2 cups coffee w/ heavy cream,2,cups,NaN,168,5.0,0.0,5.0,5.0,14.0
11,2/22/2020,12:45,2020-02-22 12:45:00,NaN,Elmo's diner breakfast burrito 2 eggs/sausage/...,NaN,NaN,NaN,657,72.0,2.7,1.4,29.0,28.0
12,2/22/2020,12:45,2020-02-22 12:45:00,NaN,Side of home fried potatoes,NaN,NaN,NaN,235,45.0,NaN,0.0,6.9,3.8
13,2/22/2020,12:45,2020-02-22 12:45:00,NaN,1 cup coffee,NaN,NaN,NaN,84,2.6,0.0,2.6,2.4,7.0
14,2/23/2020,8:00,2020-02-23 08:00:00,NaN,Standard breakfast,NaN,NaN,NaN,280,56.5,1.0,24.0,8.0,2.5
15,2/23/2020,10:00,2020-02-23 10:00:00,NaN,brown rice,1,cup,NaN,218,46.0,3.6,0.0,4.6,2.6
16,2/23/2020,10:00,2020-02-23 10:00:00,NaN,sardines,1,can,NaN,25,0.0,0.0,0.0,3.0,1.4
17,2/23/2020,10:00,2020-02-23 10:00:00,NaN,kimchi,1,cup,NaN,23,3.6,2.4,1.6,1.7,0.8
18,2/23/2020,11:00,2020-02-23 11:00:00,NaN,french bread,2,slices,NaN,348,66.0,2.8,6.0,13.8,3.0
19,2/23/2020,11:00,2020-02-23 11:00:00,NaN,Swiss cheese,4,slices,NaN,424,1.6,0.0,0.0,29.0,33.0

In [5]:
food_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           45 non-null     object
 1   time_of_day    45 non-null     object
 2   time_begin     45 non-null     object
 3   time_end       0 non-null      float64
 4   logged_food    45 non-null     object
 5   amount         25 non-null     object
 6   unit           22 non-null     object
 7   searched_food  0 non-null      float64
 8   calorie        45 non-null     int64
 9   total_carb     45 non-null     float64
 10  dietary_fiber  43 non-null     float64
 11  sugar          45 non-null     float64
 12  protein        45 non-null     float64
 13  total_fat      45 non-null     float64
dtypes: float64(7), int64(1), object(6)
memory usage: 5.1+ KB

In [6]:
food_values.count()

date             45
time_of_day      45
time_begin       45
time_end          0
logged_food      45
amount           25
unit             22
searched_food     0
calorie          45
total_carb       45
dietary_fiber    43
sugar            45
protein          45
total_fat        45
dtype: int64

In [8]:
food_values["date"].head(20)

0     2/21/2020
1     2/21/2020
2     2/21/2020
3     2/21/2020
4     2/21/2020
5     2/21/2020
6     2/21/2020
7     2/21/2020
8     2/21/2020
9     2/21/2020
10    2/22/2020
11    2/22/2020
12    2/22/2020
13    2/22/2020
14    2/23/2020
15    2/23/2020
16    2/23/2020
17    2/23/2020
18    2/23/2020
19    2/23/2020
Name: date, dtype: object

### Trabajando con Datetime
Lo primero sera convertir los datetime a el formato correcto, ya que lo esta detectando como object, lo siguiente sera colocar como index las fechas y al final agrupar por cada 2, 8 y 24 horas los datos para obtener la sumatoria y media

In [11]:
# Convertimos en fechas los datimetimes
food_values['time_begin'] = pd.to_datetime(food_values['time_begin'])

In [12]:
food_values.head()

,date,time_of_day,time_begin,time_end,logged_food,amount,unit,searched_food,calorie,total_carb,dietary_fiber,sugar,protein,total_fat
0,2020-02-21,6:30,2020-02-21 06:30:00,NaN,Salmon cakes,2,NaN,NaN,736,58.0,4.6,3.8,32.0,42.0
1,2020-02-21,6:30,2020-02-21 06:30:00,NaN,Large coffee with heavy cream,NaN,NaN,NaN,84,2.6,0.0,2.6,2.4,7.0
2,2020-02-21,8:30,2020-02-21 08:30:00,NaN,Standard breakfast,NaN,NaN,NaN,280,56.5,1.0,24.0,8.0,2.5
3,2020-02-21,13:15,2020-02-21 13:15:00,NaN,Ham and cheese sandwhich,NaN,NaN,NaN,517,28.0,2.3,3.6,28.0,32.0
4,2020-02-21,13:15,2020-02-21 13:15:00,NaN,Brownies,2 small,NaN,NaN,466,50.0,NaN,28.0,6.2,30.0

In [13]:
food_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           45 non-null     datetime64[ns]
 1   time_of_day    45 non-null     object
 2   time_begin     45 non-null     datetime64[ns]
 3   time_end       0 non-null      float64
 4   logged_food    45 non-null     object
 5   amount         25 non-null     object
 6   unit           22 non-null     object
 7   searched_food  0 non-null      float64
 8   calorie        45 non-null     int64
 9   total_carb     45 non-null     float64
 10  dietary_fiber  43 non-null     float64
 11  sugar          45 non-null     float64
 12  protein        45 non-null     float64
 13  total_fat      45 non-null     float64
dtypes: datetime64[ns](2), float64(7), int64(1), object(4)
memory usage: 5.1+ KB

In [14]:


## Se coloca indices como datetime
food_values = food_values.set_index('time_begin')
print(food_values.columns)

Index(['date', 'time_of_day', 'time_end', 'logged_food', 'amount', 'unit',
       'searched_food', 'calorie', 'total_carb', 'dietary_fiber', 'sugar',
       'protein', 'total_fat'],
      dtype='object')

In [15]:
# Empezamos por agrupar los valores importantes
# 2 horas
df_procesado_calorias_2h = food_values['calorie'].resample('2h') 
df_procesado_proteinas_2h = food_values['protein'].resample('2h') 
df_procesado_carbohidratos_2h = food_values['total_carb'].resample('2h') 
df_procesado_azucar_2h = food_values['sugar'].resample('2h')
# 8 horas 
df_procesado_calorias_8h = food_values['calorie'].resample('8h') 
df_procesado_proteinas_8h = food_values['protein'].resample('8h') 
df_procesado_carbohidratos_8h = food_values['total_carb'].resample('8h') 
df_procesado_azucar_8h = food_values['sugar'].resample('8h')
# 24 horas 
df_procesado_calorias_24h = food_values['calorie'].resample('24h') 
df_procesado_proteinas_24h = food_values['protein'].resample('24h') 
df_procesado_carbohidratos_24h = food_values['total_carb'].resample('24h') 
df_procesado_azucar_24h = food_values['sugar'].resample('24h')

### Calculamos la suma y media

En este caso tenemos que obtener el promedio y la suma de valores

In [161]:
# Definimos los metodos del dataframe a calcular
df_5min = df_procesado_5min.agg(['mean', 'median', 'max', 'min', 'std'])
df_5min_peaks = df_procesado_5min_picos.agg({
    'count': lambda x: (x == 1).sum(),
    'promedio': 'mean'
})
print(df_5min.columns)
df_5min.head(20)

Index(['mean', 'median', 'max', 'min', 'std'], dtype='object')

                         mean    median       max       min       std
datetime
2020-07-16 09:25:00  0.448949  0.064036  3.570595  0.000000  0.803402
2020-07-16 09:30:00  0.326691  0.372047  0.653164  0.016649  0.165484
2020-07-16 09:35:00  0.631900  0.631659  0.764853  0.506149  0.051198
2020-07-16 09:40:00  1.030635  1.036434  1.396314  0.658554  0.194995
2020-07-16 09:45:00  1.049776  1.044758  1.259278  0.846888  0.083042
2020-07-16 09:50:00  0.954326  0.968556  1.169628  0.759799  0.099029
2020-07-16 09:55:00  0.659374  0.639412  0.981294  0.252567  0.108660
2020-07-16 10:00:00  0.929366  0.899362  1.405279  0.702098  0.132848
2020-07-16 10:05:00  1.148832  1.090224  1.780627  0.782852  0.220604
2020-07-16 10:10:00  1.311897  1.316319  2.054700  0.899496  0.180745
2020-07-16 10:15:00  0.821845  0.787335  1.246570  0.456270  0.197061
2020-07-16 10:20:00  0.472103  0.466447  0.590676  0.282024  0.055178
2020-07-16 10:25:00  0.602545  0.627817  0.794310  0.217988  0.097485
2020-07-16 10:30:00  0.553347  0.562500  0.667519  0.461324  0.051435
2020-07-16 10:35:00  0.623980  0.566342  1.402718  0.467727  0.190109
2020-07-16 10:40:00  1.613923  1.596404  2.143269  1.085200  0.178333
2020-07-16 10:45:00  1.658225  1.703785  2.309762  0.000000  0.348827
2020-07-16 10:50:00  0.951516  0.948064  1.388630  0.326849  0.182770
2020-07-16 10:55:00  0.556582  0.543964  0.712344  0.243602  0.087331
2020-07-16 11:00:00  0.570246  0.563781  0.707221  0.474131  0.048208

In [162]:
df_5min_peaks.head()

                     count  promedio
datetime
2020-07-16 09:25:00      8  0.035088
2020-07-16 09:30:00      1  0.000833
2020-07-16 09:35:00      0  0.000000
2020-07-16 09:40:00      3  0.002500
2020-07-16 09:45:00      1  0.000833

In [163]:
df_5min.count()

mean      1866
median    1866
max       1866
min       1866
std       1866
dtype: int64

In [164]:
df_5min_peaks.count()

count       2173
promedio    1866
dtype: int64

In [165]:
# Juntamos ambos valores ahora en un solo dataframe
df_5min['total_peaks'] = df_5min_peaks['count']
df_5min['mean_peaks'] = df_5min_peaks['promedio']
df_5min.head(30)

,mean,median,max,min,std,total_peaks,mean_peaks
datetime,,,,,,,
2020-07-16 09:25:00,0.448949,0.064036,3.570595,0.000000,0.803402,8,0.035088
2020-07-16 09:30:00,0.326691,0.372047,0.653164,0.016649,0.165484,1,0.000833
2020-07-16 09:35:00,0.631900,0.631659,0.764853,0.506149,0.051198,0,0.000000
2020-07-16 09:40:00,1.030635,1.036434,1.396314,0.658554,0.194995,3,0.002500
2020-07-16 09:45:00,1.049776,1.044758,1.259278,0.846888,0.083042,1,0.000833
2020-07-16 09:50:00,0.954326,0.968556,1.169628,0.759799,0.099029,0,0.000000
2020-07-16 09:55:00,0.659374,0.639412,0.981294,0.252567,0.108660,1,0.000833
2020-07-16 10:00:00,0.929366,0.899362,1.405279,0.702098,0.132848,5,0.004167
2020-07-16 10:05:00,1.148832,1.090224,1.780627,0.782852,0.220604,1,0.000833
2020-07-16 10:10:00,1.311897,1.316319,2.054700,0.899496,0.180745,19,0.015833
2020-07-16 10:15:00,0.821845,0.787335,1.246570,0.456270,0.197061,2,0.001667
2020-07-16 10:20:00,0.472103,0.466447,0.590676,0.282024,0.055178,1,0.000833
2020-07-16 10:25:00,0.602545,0.627817,0.794310,0.217988,0.097485,1,0.000833
2020-07-16 10:30:00,0.553347,0.562500,0.667519,0.461324,0.051435,0,0.000000
2020-07-16 10:35:00,0.623980,0.566342,1.402718,0.467727,0.190109,1,0.000833
2020-07-16 10:40:00,1.613923,1.596404,2.143269,1.085200,0.178333,5,0.004167
2020-07-16 10:45:00,1.658225,1.703785,2.309762,0.000000,0.348827,14,0.011667
2020-07-16 10:50:00,0.951516,0.948064,1.388630,0.326849,0.182770,5,0.004167
2020-07-16 10:55:00,0.556582,0.543964,0.712344,0.243602,0.087331,2,0.001667
2020-07-16 11:00:00,0.570246,0.563781,0.707221,0.474131,0.048208,0,0.000000
2020-07-16 11:05:00,0.734254,0.736746,1.024838,0.185970,0.154894,2,0.001667
2020-07-16 11:10:00,0.562062,0.554885,1.624281,0.339656,0.061387,2,0.001667
2020-07-16 11:15:00,0.420224,0.430587,0.527921,0.338375,0.042788,0,0.000000
2020-07-16 11:20:00,0.269038,0.258971,0.340937,0.220550,0.033405,0,0.000000
2020-07-16 11:25:00,0.262282,0.223111,0.413671,0.037407,0.071331,0,0.000000
2020-07-16 11:30:00,0.471473,0.478987,0.646761,0.308652,0.033556,0,0.000000
2020-07-16 11:35:00,0.521757,0.523812,0.630111,0.352196,0.035051,0,0.000000
2020-07-16 11:40:00,0.518866,0.517409,0.657006,0.471303,0.025707,1,0.000833
2020-07-16 11:45:00,0.496931,0.500119,0.576321,0.444408,0.025746,0,0.000000
2020-07-16 11:50:00,0.459691,0.450811,0.582725,0.384214,0.027221,0,0.000000

In [166]:
df_5min.count()

mean           1866
median         1866
max            1866
min            1866
std            1866
total_peaks    2173
mean_peaks     1866
dtype: int64

In [167]:
df_5min.tail(30)

,mean,median,max,min,std,total_peaks,mean_peaks
datetime,,,,,,,
2020-07-23 20:00:00,0.204414,0.221550,0.678738,0.052773,0.056060,1,0.000833
2020-07-23 20:05:00,0.097975,0.097595,0.395984,0.074544,0.011951,1,0.000833
2020-07-23 20:10:00,0.196988,0.240760,0.355003,0.011792,0.074107,0,0.000000
2020-07-23 20:15:00,0.242971,0.242040,1.624184,0.110135,0.085232,3,0.002500
2020-07-23 20:20:00,0.185666,0.184412,0.815766,0.000000,0.082813,4,0.003333
2020-07-23 20:25:00,0.186624,0.185692,0.315037,0.011526,0.036058,0,0.000000
2020-07-23 20:30:00,0.182989,0.178009,0.769663,0.036125,0.056723,1,0.000833
2020-07-23 20:35:00,0.223663,0.218989,0.350895,0.038419,0.037110,1,0.000833
2020-07-23 20:40:00,0.208328,0.208744,0.263811,0.038419,0.023581,0,0.000000
2020-07-23 20:45:00,0.237853,0.235637,0.370104,0.139589,0.022729,0,0.000000
2020-07-23 20:50:00,0.208719,0.222831,0.380349,0.121661,0.036682,1,0.000833
2020-07-23 20:55:00,0.184550,0.199779,0.462310,0.012806,0.046733,2,0.001667
2020-07-23 21:00:00,0.186577,0.186973,0.332966,0.070435,0.024820,0,0.000000
2020-07-23 21:05:00,0.225522,0.226673,1.625464,0.036125,0.063485,1,0.000833
2020-07-23 21:10:00,0.260064,0.258689,0.290705,0.229234,0.016667,0,0.000000
2020-07-23 21:15:00,0.280740,0.283021,0.297108,0.080680,0.015990,0,0.000000
2020-07-23 21:20:00,0.280234,0.277898,0.527622,0.179289,0.037949,1,0.000833
2020-07-23 21:25:00,0.199335,0.194657,1.058073,0.037405,0.061703,2,0.001667
2020-07-23 21:30:00,0.148713,0.149835,0.213866,0.007684,0.034060,0,0.000000
2020-07-23 21:35:00,0.132615,0.138309,0.227953,0.006403,0.034082,0,0.000000
2020-07-23 21:40:00,0.163215,0.170325,0.429013,0.015368,0.028283,1,0.000833
2020-07-23 21:45:00,0.139974,0.134467,0.408523,0.044822,0.051004,1,0.000833
2020-07-23 21:50:00,0.146442,0.152396,0.185692,0.053787,0.021741,0,0.000000
2020-07-23 21:55:00,0.144090,0.148554,0.403401,0.006403,0.036071,1,0.000833
2020-07-23 22:00:00,0.125228,0.128064,0.350895,0.006403,0.038591,2,0.001667
2020-07-23 22:05:00,0.166588,0.172245,0.462310,0.003842,0.039264,2,0.001667
2020-07-23 22:10:00,0.223396,0.222831,0.517377,0.133186,0.032818,1,0.000833
2020-07-23 22:15:00,0.300561,0.303511,0.341930,0.206183,0.024836,0,0.000000
2020-07-23 22:20:00,0.363086,0.363701,0.393156,0.334246,0.015251,0,0.000000
2020-07-23 22:25:00,0.390997,0.390594,0.398278,0.386752,0.002382,0,0.000000

## DATASET DE 1 HORA
Aplicamos exactamente lo mismo pero ahora aplicado a una hora

In [ ]:
# Lo mismo aplicamos para 1 hora
df_procesado_1hora = food_values[' eda'].resample('1h')
# Para picos tambien
df_procesado_5min_picos = food_values['peak'].resample('1h') 
# Obtenemos el promedio
df_1hora = df_procesado_1hora.agg(['mean', 'median', 'max', 'min', 'std'])
df_1hora_peaks = df_procesado_5min_picos.agg({
    'count': lambda x: (x == 1).sum(),
    'promedio': 'mean'
})
# Juntamos ambos valores ahora en un solo dataframe
df_1hora['total_peaks'] = df_1hora_peaks['count']
df_1hora['mean_peaks'] = df_1hora_peaks['promedio']
# Removemos las columnas que no necesitamos por ahora
# df_1hora = df_1hora.drop(columns=columns_to_remove)
df_1hora.head(20)

,mean,median,max,min,std,total_peaks,mean_peaks
datetime,,,,,,,
2020-07-16 09:00:00,0.765428,0.766203,3.570595,0.000000,0.323079,14,0.001885
2020-07-16 10:00:00,0.937013,0.816151,2.309762,0.000000,0.435768,56,0.003889
2020-07-16 11:00:00,0.472971,0.488726,1.624281,0.037407,0.141086,6,0.000417
2020-07-16 12:00:00,0.341072,0.293550,2.103368,0.000000,0.180508,11,0.000764
2020-07-16 13:00:00,1.833972,1.805061,3.420278,0.260252,0.560089,197,0.013681
2020-07-16 14:00:00,2.588916,2.678745,4.620881,0.585622,0.635568,126,0.008750
2020-07-16 15:00:00,3.403984,3.323417,6.045711,1.045498,0.759495,251,0.017431
2020-07-16 16:00:00,3.971467,3.568948,10.789403,0.000000,1.725551,260,0.018056
2020-07-16 17:00:00,3.402337,3.443804,7.072930,0.346129,1.016422,231,0.016042
2020-07-16 18:00:00,0.635618,0.594518,1.457788,0.000000,0.317827,54,0.003750
2020-07-16 19:00:00,0.717656,0.359881,4.212781,0.003842,0.985593,22,0.001528
2020-07-16 20:00:00,0.629634,0.617571,1.722995,0.007684,0.244369,37,0.002569
2020-07-16 21:00:00,0.453420,0.470022,2.102087,0.000000,0.093331,20,0.001389
2020-07-16 22:00:00,0.474247,0.471570,2.590238,0.020758,0.067109,15,0.001042
2020-07-16 23:00:00,0.194721,0.200058,1.717873,0.000000,0.148204,21,0.001458
2020-07-17 00:00:00,1.050356,0.962152,5.904090,0.242322,1.004802,17,0.001181
2020-07-17 01:00:00,2.816141,2.798491,6.741792,0.941661,1.356731,81,0.005625
2020-07-17 02:00:00,6.257662,6.205173,11.774044,2.649288,1.793663,193,0.013403
2020-07-17 03:00:00,6.989505,6.935537,14.484730,1.464490,3.343017,278,0.019306
2020-07-17 04:00:00,6.659092,7.442429,12.710264,2.841395,2.330753,108,0.007500

In [169]:
# Separar los cuartiles en columnas individuales
# Obtenemos los quantiles
df_5min_quantil1 = df_procesado_5min.quantile(0.25)
df_5min_quantil3 = df_procesado_5min.quantile(0.75)
df_1hora_quantil1 = df_procesado_1hora.quantile(0.25)
df_1hora_quantil3 = df_procesado_1hora.quantile(0.75)
df_5min['q1'] = df_5min_quantil1
df_5min['q3'] = df_5min_quantil3
df_5min.head(10)
# df_1hora[['q1', 'q3']] = [df_1hora_quantil1,df_1hora_quantil3]

,mean,median,max,min,std,total_peaks,mean_peaks,q1,q3
datetime,,,,,,,,,
2020-07-16 09:25:00,0.448949,0.064036,3.570595,0.000000,0.803402,8,0.035088,0.005123,0.335883
2020-07-16 09:30:00,0.326691,0.372047,0.653164,0.016649,0.165484,1,0.000833,0.139598,0.452092
2020-07-16 09:35:00,0.631900,0.631659,0.764853,0.506149,0.051198,0,0.000000,0.591957,0.670080
2020-07-16 09:40:00,1.030635,1.036434,1.396314,0.658554,0.194995,3,0.002500,0.858042,1.190439
2020-07-16 09:45:00,1.049776,1.044758,1.259278,0.846888,0.083042,1,0.000833,0.986486,1.117119
2020-07-16 09:50:00,0.954326,0.968556,1.169628,0.759799,0.099029,0,0.000000,0.877625,1.036434
2020-07-16 09:55:00,0.659374,0.639412,0.981294,0.252567,0.108660,1,0.000833,0.571465,0.725220
2020-07-16 10:00:00,0.929366,0.899362,1.405279,0.702098,0.132848,5,0.004167,0.819621,1.018824
2020-07-16 10:05:00,1.148832,1.090224,1.780627,0.782852,0.220604,1,0.000833,1.001854,1.325974
2020-07-16 10:10:00,1.311897,1.316319,2.054700,0.899496,0.180745,19,0.015833,1.179948,1.420747

In [170]:
df_5min.count()

mean           1866
median         1866
max            1866
min            1866
std            1866
total_peaks    2173
mean_peaks     1866
q1             1866
q3             1866
dtype: int64

In [171]:
# Igual con 1hora de dataset
df_1hora['q1'] = df_1hora_quantil1
df_1hora['q3'] = df_1hora_quantil3
df_1hora.head(10)

,mean,median,max,min,std,total_peaks,mean_peaks,q1,q3
datetime,,,,,,,,,
2020-07-16 09:00:00,0.765428,0.766203,3.570595,0.000000,0.323079,14,0.001885,0.575307,1.013381
2020-07-16 10:00:00,0.937013,0.816151,2.309762,0.000000,0.435768,56,0.003889,0.576588,1.232383
2020-07-16 11:00:00,0.472971,0.488726,1.624281,0.037407,0.141086,6,0.000417,0.408548,0.536886
2020-07-16 12:00:00,0.341072,0.293550,2.103368,0.000000,0.180508,11,0.000764,0.223111,0.412657
2020-07-16 13:00:00,1.833972,1.805061,3.420278,0.260252,0.560089,197,0.013681,1.403703,2.273628
2020-07-16 14:00:00,2.588916,2.678745,4.620881,0.585622,0.635568,126,0.008750,2.208517,3.023257
2020-07-16 15:00:00,3.403984,3.323417,6.045711,1.045498,0.759495,251,0.017431,2.814500,3.837532
2020-07-16 16:00:00,3.971467,3.568948,10.789403,0.000000,1.725551,260,0.018056,2.614298,5.054976
2020-07-16 17:00:00,3.402337,3.443804,7.072930,0.346129,1.016422,231,0.016042,2.805124,4.029639
2020-07-16 18:00:00,0.635618,0.594518,1.457788,0.000000,0.317827,54,0.003750,0.353157,0.845607

In [172]:
df_1hora.count()

mean           161
median         161
max            161
min            161
std            161
total_peaks    182
mean_peaks     161
q1             161
q3             161
dtype: int64

## LIMPIEZA DE DATOS
Algunas filas contienen datos NaN, vamos a limpiarlos

In [173]:
df_5min_cleaned = df_5min.dropna(subset=['mean'])
df_1hora_cleaned = df_1hora.dropna(subset=['mean'])
print('Cantidad de datos de dataset 5 min limpiado: ' + str(df_5min_cleaned.count()))
print('Cantidad de datos de dataset 1 hora limpiado: ' + str(df_1hora_cleaned.count()))

Cantidad de datos de dataset 5 min limpiado: mean           1866
median         1866
max            1866
min            1866
std            1866
total_peaks    1866
mean_peaks     1866
q1             1866
q3             1866
dtype: int64
Cantidad de datos de dataset 1 hora limpiado: mean           161
median         161
max            161
min            161
std            161
total_peaks    161
mean_peaks     161
q1             161
q3             161
dtype: int64

In [174]:
# Exportamos los resultados en un csv
df_5min_cleaned.to_csv("EDA_5min.csv")
df_1hora_cleaned.to_csv("EDA_1hora.csv")

### ARCHIVOS CSV GENERADOS CON EXITO PARA 5 MIN Y 1 HORA